const ROUTES = {
  PLAYER: 'PLAYER',
  READ: 'READ',
  SETTINGS: 'SETTINGS',
  BIBLE_BOOK_CHAPTERS: 'BIBLE_BOOK_CHAPTERS',
  READ_CHAPTERS: 'READ_CHAPTERS',
  BIBLE_BOOKS: 'BIBLE_BOOKS',
  BIBLE_LIST: 'BIBLE_LIST',
  LISTEN_LIST: 'LISTEN_LIST',
  FOLDER_LIST: 'FOLDER_LIST',
  LESSON_FOLDERS: 'LESSON_FOLDERS',
  LESSONS_LIST: 'LESSONS_LIST',
  READ_LESSON: 'READ_LESSON',
  READ_TAB: 'READ_TAB',
  LISTEN_TAB: 'LISTEN_TAB',
};

const PARAMS = {
  HEADER_BUTTON_RIGHT_PLAYER_ACTION: 'HEADER_BUTTON_RIGHT_PLAYER_ACTION',
  HEADER_PLAY_FUNCTION_PARAM: 'HEADER_PLAY_FUNCTION_PARAM',
  HEADER_ACTION: 'HEADER_ACTION',
  PLAYER_TITLE: 'PLAYER_TITLE',
  HAS_ERROR: 'HAS_ERROR',
  PLAYER: 'PLAYER',
};

const KEYS = {
  APP_STORAGE_KEY: '@BAIBEL',
  APP_THEME: 'APP_THEME',
};

export default {
  ROUTES,
  PARAMS,
  KEYS,
};
